API_HOST_URL: 'https://k8s.schoddle.com/'
ECOMMERCE_URL: 'https://ecommerce.k8s.schoddle.com'
ENVIRONMENT_DISPLAY_NAME: 'Schoddle by Sujit Patel'
PLATFORM_NAME: 'Schoddle'
PLATFORM_DESTINATION_NAME: 'schoddle.com'
FEEDBACK_EMAIL_ADDRESS: 'admin@schoddle.com'

APP_REWIEWS_ENABLED: true
APP_UPDATE_URIS: 'https://play.google.com/store/apps/details?id={application_id}'
ANNOUNCEMENTS_ENABLED: true
BADGES_ENABLED: true
CERTIFICATES_ENABLED: true
COURSE_DATES_ENABLED: true
COURSE_ENROLLMENT_ENABLED: true
COURSE_VIDEO_ENABLED: true
COURSE_SHARING_ENABLED: true
DISCUSSIONS_ENABLED: true
DISCUSSIONS_ENABLE_PROFILE_PICTURE_PARAM: true
DOWNLOAD_TO_SD_CARD_ENABLED: true
NEW_COURSE_NAVIGATION_ENABLED: true
NEW_LOGISTRATION_ENABLED: true
PUSH_NOTIFICATION: true
REGISTRATION_ENABLED: true
TAB_LAYOUTS_ENABLED: true
USING_VIDEO_PIPELINE: true
USER_PROFILES_ENABLED: true
VIDEO_TRANSCRIPT_ENABLED: true
WHATS_NEW_ENABLED: true

COURSE_ENROLLMENT:
  TYPE: 'NATIVE'

DISCOVERY:
  COURSE:
    TYPE: native
    NATIVE:
      SEARCH_ENABLED: true
      SUBJECT_FILTER_ENABLED: true
      SUBJECT_DISCOVERY_ENABLED: true

FACEBOOK:
  ENABLED: false
  FACEBOOK_APP_ID: '618852489233566'

FIREBASE:
  ENABLED: false
  ANALYTICS_SOURCE: 'firebase'
  CLOUD_MESSAGING_ENABLED: true
  PROJECT_NUMBER: 'x669296609754'
  PROJECT_ID: 'minischoolapp'
  OAUTH_CLIENT_ID: 'x669296609754-q9iacqq19u0tgkbjcv8t2uppmob658ap.apps.googleusercontent.com'
  CURRENT_KEY: 'xAIzaSyD6vQTURgT4R51SII0P4OYW3Mgk2QOleoM'
  MOBILE_SDK_APP_ID: 'x1:669296609754:android:2490f3abd2b65f69b2d8e3'

GOOGLE:
  ENABLED: false
  GOOGLE_PLUS_KEY: '1059399383530-olv5ms6u9egqie4umprcai6dsaqkpnrb.apps.googleusercontent.com'

YOUTUBE_PLAYER:
  ENABLED: true
  API_KEY: 'AIzaSyCZlUjacYqD8M8e5utLWAZDT2gz1tREiLw'
